DROP TABLE ROLE CASCADE CONSTRAINTS PURGE;

CREATE TABLE ROLE (
GRADE			VARCHAR2(50) primary key,		-- 유저 등급
INV_ACCESS		NUMBER(2)			-- 초대 권한
)

SELECT *
FROM ROLE;

INSERT INTO ROLE
VALUES('master', 1);

INSERT INTO ROLE
VALUES('sub', 1);

INSERT INTO ROLE
VALUES('normal', 0);
